// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW9giVZRvuctEviZZaettxUSODb1yER8I',
    appId: '1:685347292831:web:85114d9ba1342f04a904aa',
    messagingSenderId: '685347292831',
    projectId: 'chat-app-eb417',
    authDomain: 'chat-app-eb417.firebaseapp.com',
    storageBucket: 'chat-app-eb417.firebasestorage.app',
    measurementId: 'G-FX6FS27H53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1nmY8MFza_atB8pkwlMpfv47n5XqRnCI',
    appId: '1:685347292831:android:3c16dfc1deeb029da904aa',
    messagingSenderId: '685347292831',
    projectId: 'chat-app-eb417',
    storageBucket: 'chat-app-eb417.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL0XHWpWQFlZaf8L_Rk9juXE6R2uznuuk',
    appId: '1:685347292831:ios:c78a0ff5ede5d66da904aa',
    messagingSenderId: '685347292831',
    projectId: 'chat-app-eb417',
    storageBucket: 'chat-app-eb417.firebasestorage.app',
    iosBundleId: 'com.example.eduPlatt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL0XHWpWQFlZaf8L_Rk9juXE6R2uznuuk',
    appId: '1:685347292831:ios:c78a0ff5ede5d66da904aa',
    messagingSenderId: '685347292831',
    projectId: 'chat-app-eb417',
    storageBucket: 'chat-app-eb417.firebasestorage.app',
    iosBundleId: 'com.example.eduPlatt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW9giVZRvuctEviZZaettxUSODb1yER8I',
    appId: '1:685347292831:web:fa02a74a44030275a904aa',
    messagingSenderId: '685347292831',
    projectId: 'chat-app-eb417',
    authDomain: 'chat-app-eb417.firebaseapp.com',
    storageBucket: 'chat-app-eb417.firebasestorage.app',
    measurementId: 'G-5D2S6BQDWW',
  );
}
